apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streaming.name" . }}-redis
  labels:
    {{- include "streaming.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.image.redis }}
          args: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: 5
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "streaming.name" . }}-redis
  labels:
    {{- include "streaming.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 6379
      targetPort: redis
